defaultDataMeshRegistryUrl: /DataMeshRegistryPetsExample.yaml

iconMap:
  dataproduct: /icons/dataproduct.svg
  database: /icons/database.svg
  table: /icons/table.svg
  oracle: /icons/oracle.svg
  rdsoracle: /icons/rdsoracle.svg
  rdsaurora: /icons/rdsaurora.svg
  rdsmariadb: /icons/rdsmariadb.svg
  rdsmysql: /icons/rdsmysql.svg
  rdspostgresql: /icons/rdspostgresql.svg
  rdssqlserver: /icons/rdssqlserver.svg
  sharepoint: /icons/sharepoint.svg
  reltio: /icons/reltio.svg
  veevavault: /icons/veeva.svg
  ftp: /icons/ftp.svg
  salesforce: /icons/salesforce.svg
  sap: /icons/sap.svg
  s3: /icons/s3.svg
  redshift: /icons/redshift.svg
  atlassian: /icons/atlassian.svg
  jira: /icons/jira.svg
  googleanalytics: /icons/googleanalytics.svg
  servicenow: /icons/servicenow.svg
  databricks: /icons/databricks.svg
  deltalake: /icons/deltalake.svg
  odata: /icons/odata.svg
  snowflake: /icons/snowflake.svg
  api: /icons/api.svg
  iceberg: /icons/iceberg.svg
  kafka: /icons/kafka.svg
  kinesis: /icons/kinesis.svg
  powerbi: /icons/powerbi.svg
  agent: /icons/robot.svg
  application: /icons/application.svg

domainPalette:
  - "#fee2e2"
  - "#f3e8ff"
  - "#fef3c7"
  - "#ffedd5"
  - "#e0e7ff"
  - "#dbeafe"
  - "#dcfce7"

tiers:
  datasource:
    label: Data Source
    color: "#e2e8f0"
    bannerColor: "#cbd5e1"
    columnNumber: 1
  sourcealigned:
    label: Data Product (Source Aligned)
    color: "#bfdbfe"
    bannerColor: "#93c5fd"
    columnNumber: 2
  curated:
    label: Data Product (Curated)
    color: "#bfdbfe"
    bannerColor: "#93c5fd"
    columnNumber: 3
  consumeraligned:
    label: Data Product (Consumer Aligned)
    color: "#bfdbfe"
    bannerColor: "#93c5fd"
    columnNumber: 4
  application:
    label: Application
    color: "#e2e8f0"
    bannerColor: "#cbd5e1"
    columnNumber: 5
  agent:
    label: Agent
    color: "#e2e8f0"
    bannerColor: "#cbd5e1"
    columnNumber: 5
